import "@/app/globals.css?url"
import { ReactNode } from "react"
import type { Metadata } from "next"
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
	title: "Vault - Suas senhas seguras, finalmente",
	description: "Generated by create next app",
}

type RootLayoutProps = {
	children: Readonly<ReactNode>
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="pt-br">
			<body className={`${inter.className}`}>{children}</body>
		</html>
	)
}